version: '3.9'

services:

  db:
    image: mariadb:10.5.8
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: dorime
    container_name: mariadb_donalo

  adminer:
    image: adminer:4.8.0
    ports:
      - 8080:8080
    container_name: adminer_donalo
  php:
    build: .
    ports:
      - 9000:80
    volumes:
      - .:/var/www/html
    container_name: php_donalo
